spring.datasource.url=jdbc:h2:mem:aestheticsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=gus
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.show-sql=true