# H2 - banco em memória, sobe junto com a aplicação
spring.datasource.url=jdbc:h2:mem:aestheticsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=gus
spring.datasource.password=1234

# Hibernate cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=create-drop

# Console visual do H2 acessível em http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Mostra o SQL gerado pelo Hibernate no console
spring.jpa.show-sql=true